import Footer from "./components/Footer.js"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
